### PR TITLE
Fall back to artist and title after track id when sorting in albums

### PR DESCRIPTION
**Pull request by lbonn**
If files cannot be sorted according to the query, fall back to ascending/descending file names.

One use case is a loose compilation of files with same album, album artist, and no track numbers. File order was then undetermined, in practice depended on insertion order in the database.

### CODE REVIEW

**Comment by deluan** [comment]
Hey, thanks for the PR. But can you elaborate a bit more about the situation you are trying to fix this? Is it in the Web UI or in the Subsonic API? Can't we just add `title` to the 'sort by album' config the mediafile_repository:
```
	r.sortMappings = map[string]string{
		"artist": "order_artist_name asc, album asc, disc_number asc, track_number asc",
		"album":  "order_album_name asc, disc_number asc, track_number asc, title asc",
		"random": "RANDOM()",
	}
```

Also, the tests are failing (see the errors in the pipeline)

**Comment by lbonn** [comment]
@deluan sorry, about the typo. Missed it in the test outputs the first time.

The sorting issue is both in the UI and API actually: I have this folder in which I download mixes (songs are added regularly).
Files are named `artist - year - title.mp3`, have different artists and titles but no track id and same album and album artist + the iTune TCMP tag so that they are gathered in the same album by Navidrome.
In this case, it makes more sense to browse files by artists alphabetically and that's why I chose this naming scheme as usually media player end up sorting by file names if they can't do better.

Right now, it seems that the files end up being sorted by their id in the database and I don't think there are a lot of use case where this makes sense (both in the UI and API). So the change is to fall back to using paths when nothing else works.

Or we could add sort by artist then sort by title for the album sort?

**Comment by deluan** [comment]
I see... Did you test your changes? I mean, this would only be used for the Web UI. Currently the query used for the Subsonic API is here: https://github.com/deluan/navidrome/blob/21f7c1906dc52fbcffae866f7ce66f5750f4e1ca/persistence/mediafile_repository.go#L79-L80

so your change would not change the sort order for Subsonic clients.

Also, if you say the album is the same for all tracks, and they don't have track number nor disc number, adding `title asc` at the end of the album sort (as I proposed in my first comment) should give what you want. At least in the Web UI, then we could change the `FindByAlbum` function above to use the same sort option. Can you please try it?

**Comment by lbonn** [comment]
Thanks for your help!

Ah I see, I assumed that the UI was also using the Subsonic API. So I tested my changes which worked on the WebUI and various sort queries with curl requests.

I am having issues testing from my Subsonic client (Ultrasonic) and Navidrome running with `make dev`: it is getting 404 apparently because it's not sending `Accept: */*`. This is not happening when I run a full instance, so this might be related to the proxy used by react?

Unfortunately your first suggestion is not enough, to apply in the UI. I also had to replace `discNumber asc, trackNumber asc` with `album` in https://github.com/deluan/navidrome/blob/master/ui/src/album/AlbumShow.js#L25 (also, `album asc` does not work as it's using the complete string as a key).

The necessary change would actually be to add `artist asc, title asc` as the songs have different artists) but maybe that's a bit specific that's why I thought that file names would be more flexible.

**Comment by lbonn** [comment]
I've pushed another version, closer to your suggestion. It's working in the UI and from the API (tested with Ultrasonic)

**Comment by deluan** [comment]
This looks great! I'll do some more testing before merging and maybe get rid of the `FindByAlbum` or at least make it use the `sortMapping` to avoid duplication.

**Comment by deluan** [comment]
Hey, I did the changes I talked about, and also changed the mapping to use the `order_*` fields. Let me know if this works for you so we can merge it

**Comment by lbonn** [comment]
Nice, yes it works in the app and ui!

**Pull request merged**
