### PR TITLE
Add HTTP security headers

### LINKED ISSUE #248: Implementation of HTTP security headers
Please use https://securityheaders.com/ if you want to do some testing yourself and get some feedback. But let's drop in a few thoughts on this:

Content-Security-Policy and Feature-Policy
--
We should definitely implement this headers as strict as possible to only use the browser features Navidrome needs. Meaning disabling features like webcam, geo, microphone et cetera. This would limit the possibilities extremely when an XSS injection is possible.

X-Frame-Options
--
This Header we should also include with the "same-origin" option by default. Meaning simply that it isn't possible to frame Navidrome (iframes) and do some clickjacking attacks. Although I can imaging in some cases some advanced users might want to configure and frame it anyway, so I suggest this header should be default on "same-origin" but configurable in Settings.

X-Content-Type-Options
--
Mainly for older browsers but lets add it with the "nosniff" option. Doesn't hurt anyone. Possibly prevents content type sniffing.

X-XSS-Protection
--
Yes, should use with "1; mode=block" value. Does not work in all browsers but won't affect browsers that don't support it. Should be enabled in the browser by default in most cases. Just a case of better be safe then sorry when XSS is possible and the browser config sucks.

Referrer-Policy
--
Only relevant when we start to refer to external URL's, which I believe is not the case currently. Nevertheless I would already set it up with the "no-referrer" or "same-origin".

Other HTTP security headers such as Expect-CT, Expect-Staple, HSTS, HPKP should be left to advanced users to configure themselves, only when SSL is enabled. Maybe we could facilitate adding custom HTTP headers from a config file?

### PR DESCRIPTION
**Pull request by deluan**
Closes #248

### CODE REVIEW

**Comment by deluan** [comment]
@jvoisin @madcatsu Can someone please validate the [options](https://github.com/unrolled/secure#available-options) I used? 

Also, I didn't quite figure out the CSP configuration. Do we need to add the full server address? In the `secure` library example, it uses a "nonce" value: `Content-Security-Policy: script-src 'nonce-a2ZobGFoZg=='`

Thanks for the help

**Comment by madcatsu** [comment]
@deluan these closely align to a similar config I use in [Traefik](https://doc.traefik.io/traefik/). Some feedback for you:

`ForceSTSHeader: true` 

Should be false (which is the default) as this may cause issues for people running Navidrome behind a proxy, in theory this would only be needed if Navidrome was providing the HTTPS connection with an installed cert.

`ContentSecurityPolicy: "default-src 'self'"` 

I'm currently using `default-src https://*.subdomain.domain; script-src https://*.subdomain.domain 'unsafe-inline'` (replacing subdomain.domain with my actual values). These are just defaults because not all of my endpoints are serving HTML `<script>` blocks with nonces which means I have to unsafe-inline. Using the `$NONCE` template would be preferred for Navidrome.

**Comment by jvoisin** [comment]
`BrowserXssFilter:   true,` can 'should be removed, it's useless nowadays at beast, harmful at worse.

**Comment by deluan** [comment]
> `ForceSTSHeader: true`

@madcatsu Ops, I removed all other STS options and forgot this one. For the CSP Nonce, from what I understand I have to get the generated nonce and set it as an arg to my <script> tags, right?

As for the CSP configuration, using nonces with CRA seems to be a non trivial change, and requires introducing 3 new JS dependencies: https://medium.com/@nrshahri/csp-cra-324dd83fe5ff#ae56 

Any ideas?

@jvoisin Yep, forgot about it. Removed!

**Comment by madcatsu** [comment]
Out of curiosity, is there much inline JS in the frontend? Is the JS dynamic? 

If not, why not just create a hash and set the CSP to include the hash of the inline script if it's static? External scripts shouldn't require a nonce or hash from what I understand about CSP if you set `script-src` to `self`

**Comment by deluan** [comment]
There are two pieces of inline JS: One for the config options that I have control of and can add a nonce/hash, and another that's injected by the CRA WebPack config, that I have no control at all. For the later, I'd have to do something similar to what the linked post above explains, which is a hassle....

**Pull request merged**
