### PR TITLE
Add German localization

### PR DESCRIPTION
**Pull request by TheForcer**
Hi, I thought adding a German translation would be pretty nice :) 

I haven't really worked with npm before, so I hope the PR is alright. The translation works fine on my dev container.

### CODE REVIEW

**Comment by deluan** [comment]
Thanks! But this is just bad timing.... Today we started moving to a new translation platform (no code changes necessary), and someone from our Discord channel offered to do the German translation and finished it... a few hours before your PR! 

Sorry for that.... Maybe I can add you to the platform we are evaluating (POEditor), and you can help review the translation?

**Comment by TheForcer** [comment]
Aw, that's unfortunate. But yeah, I'd gladly help out with reviewing. I think you can add me to the translation project with my email "git@theforcer.de"

**Comment by brianpierson2020** [comment]
Hi @TheForcer,
What a coincidence indeed. I've added you to the German project on POEditor. Feel free to check and correct translations if needed. Thanks for your help.

**Comment by deluan** [comment]
Thanks @brianpierson2020 and @TheForcer, I'm closing this now.

**Pull request closed without merging**
