### PR TITLE
Add Desktop Notifications

### PR DESCRIPTION
**Pull request by srichter**
Adds functionality and a setting for Desktop Notifications. Also establishes the settings key on the state and actions/reducers for it.

### CODE REVIEW

**Comment by deluan** [comment]
Great contribution! I just tested it and seems like it is missing moving the switch back to "Off" if the user blocks the notification, right?

**Comment by deluan** [comment]
Fixed. The issue was that the BooleanInput component gets its value from the wrapping form, and cannot be changed directly. I replaced it with a simple Switch component (with label and helper text), so the value can be controlled directly by the `checked` property.

LGTM otherwise, so take a look and if you don't have any other concerns, it's ready to be merged

**Comment by srichter** [comment]
Ahh, that makes sense now how you implemented that. I tested it all and it works just as it should, great job!

**Comment by count00zero** [comment]
Does the current implementation also include the albumart/cover like Airsonic or Ampache?

**Comment by deluan** [comment]
I see the code includes the cover, but I don't see it in the notifications... @srichter did you get this working?

**Comment by srichter** [comment]
I'm seeing the cover in the notifications on macOS. I believe it may have been the case that the cover image wouldn't show unless the app was bundled in Electron (as it'd only show the browser's icon otherwise), but I'm seeing the cover image in both Firefox and Chrome now.

**Comment by count00zero** [comment]
unfortunately: neither on windows nor on linux (and neither with firefox nor chrome{ium) I can see the coverart.
Zwischenablage02

**Comment by srichter** [comment]
Does the image show if you try this demo? https://www.bennish.net/web-notifications.html

**Comment by count00zero** [comment]
yes, it does ... 
Zwischenablage02

**Comment by srichter** [comment]
Do you access your Navidrome instance via https? What kind of file are you playing? Is the cover-art embedded in the file?

**Comment by count00zero** [comment]
yes, I access navidrome via https (through a reverse nginx proxy); all files have embedded cover-art (mp3 & flac) and cover-art jpegs resing alongside the music files in the same directory.

**Comment by deluan** [comment]
I'm also cannot see the cover art, but I see a wrong request for getCoverArt in the Network tab, it is duplicating the `baseUrl`:
```
https://my.server.com/navidrome/navidrome/rest/getCoverArt&u=deluan&...
````
where it should be:
```
https://my.server.com/navidrome/rest/getCoverArt&u=deluan&...
```

So, maybe it is an issue for users that set their BaseURL?

Hey @count00zero are you using a `BaseURL` configuration?

**Comment by deluan** [comment]
So I pushed a fix for this, a81ef092. Will do more testing in my deployed environment.

**Comment by count00zero** [comment]
Sorry for late reply: yes, I use BaseURL and you already fixed it I see :)
Now the caover art is included in the notification!
Great work and many thanks!!!

**Comment by srichter** [comment]
Good catch! I must've seen `baseUrl` used elsewhere and thought it needed to be applied to the cover URL of a track 😅. Notifications still work for me with the change (and no BaseUrl set)

**Pull request merged**
