### PR TITLE
improve spanish translation

### PR DESCRIPTION
**Pull request by victorhck**

### CODE REVIEW

**Comment by deluan** [comment]
Thanks for this! 

Hey @jacostag, can you please review this? Thanks

**Comment by deluan** [comment]
Hey @victorhck , I was reviewing your changes, and I'm not sure if the case changes are actually an improvement, ex: "Reproducir Después" is better then "Reproducir después".... I think the current translations are pretty consistent with other mainstream players, like Spotify and Apple Music. Do you have any reasons to think otherwise?

**Comment by victorhck** [comment]
Yes, because in spanish that is not right. Check out:
https://www.spanishdict.com/guide/capitalization-in-spanish

**Comment by deluan** [comment]
We use the same capitalization in Portuguese, but at least in Brazil you can find softwares translated with the same capitalization as English. But I'm not a Spanish speaking person, so I'll take your word ;)

**Pull request merged**
